LANGUAGES={
    "English":{
        "app_title":"Vault100 - Secure Financial Engine",
        "login_title":"Vault100",
        "login_subtitle":"Secure Financial Engine",
        "username":"Username",
        "password":"Password",
        "enter_vault":"Enter the Vault",
        "no_account":"Don't have an account? Sign up",
        "invalid_credentials":"Invalid username or password.",

        "signup_title":"Create Account",
        "signup_subtitle":"Sign up for Vault100",
        "choose_username":"Choose a Username",
        "choose_password":"Choose a Password",
        "confirm_password":"Confirm Password",
        "create_account":"Create Account",
        "have_account":"Already have an account? Log in",
        "passwords_no_match":"Passwords do not match.",
        "username_min":"Username must be at least 3 characters.",
        "password_min":"Password must be at least 4 characters.",
        "username_taken":"Username already taken.",
        "register_success":"Account created! Redirecting to login page.",
        "register_fail":"Registration failed. Try again.",

        "dashboard_title":"Vault100 Dashboard",
        "total_balance":"Total Net Balance",
        "quick_add":"Quick Add",
        "amount":"Amount (TL)",
        #"amount_usd":"Amount (USD)",
        #"amount_eur":"Amount (EUR)",
        "type":"Type",
        "income":"Income",
        "expense":"Expense",
        "category":"Category",
        "description":"Description",
        "add_required":"Amount and Type are required.",
        "add_number":"Amount must be a number.",
        "tx_history":"Transaction History",
        "no_tx":"No transactions yet",
        "date":"Date",
        "del":"Del",
        "analysis":"Analysis",
        "total_income":"Total Income",
        "total_expense":"Total Expense",
        "net":"Net",
        "expense_by_cat":"Expense by Category",
        "total_spent":"Total Spent",
        "no_expense_data":"No expense data",
        "export_title":"Export Statement",
        "from_date":"From (DD-MM-YYYY)",
        "to_date":"To (DD-MM-YYYY)",
        "export_btn":"Export",
        "export_saved":"Saved: ",
        "export_fail":"Export failed.",
        "optional":"optional",
        "logout":"Logout",

        "admin_title":"Admin — User Management",
        "role":"Role",
        "remove":"Remove",
        "add_user_title":"Add New User",
        "add_btn":"Add",
        "all_fields":"All fields required.",
        "user_exists":"Username already exists.",

        "food":"Food",
        "rent":"Rent",
        "salary":"Salary",
        "bills":"Bills",
        "fun":"Fun",
        "general":"General",

        "language":"Language",
    },

    "Turkish":{
        "app_title":"Vault100 - Güvenli Finans Motoru",
        "login_title":"Vault100",
        "login_subtitle":"Güvenli Finans Motoru",
        "username":"Kullanıcı Adı",
        "password":"Şifre",
        "enter_vault":"Kasaya Gir",
        "no_account":"Hesabın yok mu? Kayıt ol",
        "invalid_credentials":"Geçersiz kullanıcı adı veya şifre.",
        "signup_title":"Hesap Oluştur",
        "signup_subtitle":"Vault100'e kayıt ol",
        "choose_username":"Kullanıcı Adı Seç",
        "choose_password":"Şifre Seç",
        "confirm_password":"Şifreyi Onayla",
        "create_account":"Hesap Oluştur",
        "have_account":"Zaten hesabın var mı? Giriş yap",
        "passwords_no_match":"Şifreler eşleşmiyor.",
        "username_min":"Kullanıcı adı en az 3 karakter olmalı.",
        "password_min":"Şifre en az 4 karakter olmalı.",
        "username_taken":"Bu kullanıcı adı zaten alınmış.",
        "register_success":"Hesap oluşturuldu!",
        "register_fail":"Kayıt başarısız. Tekrar deneyin.",
        "dashboard_title":"Vault100 Paneli",
        "total_balance":"Toplam Net Bakiye",
        "quick_add":"Hızlı Ekle",
        "amount":"Tutar (TL)",
        "type":"Tür",
        "income":"Gelir",
        "expense":"Gider",
        "category":"Kategori",
        "description":"Açıklama",
        "add_required":"Tutar ve Tür zorunludur.",
        "add_number":"Tutar sayı olmalıdır.",
        "tx_history":"İşlem Geçmişi",
        "no_tx":"Henüz işlem yok",
        "date":"Tarih",
        "del":"Sil",
        "analysis":"Analiz",
        "total_income":"Toplam Gelir",
        "total_expense":"Toplam Gider",
        "net":"Net",
        "expense_by_cat":"Kategoriye Göre Gider",
        "total_spent":"Toplam Harcama",
        "no_expense_data":"Gider verisi yok",
        "export_title":"Dışa Aktar",
        "from_date":"Başlangıç (GG-AA-YYYY)",
        "to_date":"Bitiş (GG-AA-YYYY)",
        "export_btn":"Dışa Aktar",
        "export_saved":"Kaydedildi: ",
        "export_fail":"Dışa aktarma başarısız.",
        "optional":"isteğe bağlı",
        "logout":"Çıkış Yap",
        "admin_title":"Admin — Kullanıcı Yönetimi",
        "role":"Rol",
        "remove":"Kaldır",
        "add_user_title":"Yeni Kullanıcı Ekle",
        "add_btn":"Ekle",
        "all_fields":"Tüm alanlar zorunludur.",
        "user_exists":"Kullanıcı adı zaten mevcut.",
        "food":"Yemek",
        "rent":"Kira",
        "salary":"Maaş",
        "bills":"Faturalar",
        "fun":"Eğlence",
        "general":"Genel",
        "language":"Dil",
    }
}
# falling back to eng if key is missing
def get(lang_name,key):
    return LANGUAGES.get(lang_name,LANGUAGES["English"]).get(key,LANGUAGES["English"].get(key,key))
#testing:
#print(LANGUAGES.keys())
#print(LANGUAGES["English"]["app_title"])